### ISSUE TITLE
Urgent: Update Library License For Enterprise usage

### ISSUE THREAD

**Issue by iutsalo-de-gh** [esafirm/android-image-picker#360]
Hey, kudos to @esafirm and all contributors to this repository. 

I noticed the link at the bottom the ReadMe [You can find the original license here](https://raw.githubusercontent.com/esafirm/ImagePicker/master/ORIGINAL_LICENSE) does not work. 
It takes you to a "404 not found" page.

## Expected: Expecting Apache 2.0 License or similar
There doesn't seem to be a clear standardized license for this library. Currently considering removing this library from my dependencies since it doesn't have the legally approved licenses required by the enterprise. I was expecting there to be an MIT or Apache 2.0 License, but it seems like there isn't one and it's more like a disclaimer template license. 

## Suggestions
Can the license be updated to one of the following
- Apache 2.0 License or
- MIT license or any other similar license.

This would help enterprises testing out the functionality provided by this library do so without fear of any legal repercussions.

Please provide updates to this request in a timely manner. @esafirm

**Comment by esafirm** [comment]
I think I will update the license to MIT due to there's little to no correlation to the original project. Also, the original project take some code from here and not giving any credit whatsoever 😬

Example: 
[CameraModule in AIP](https://github.com/esafirm/android-image-picker/blob/9af45dbf16aa9fb1a8e2f97b6089f164dd4e7dec/imagepicker/src/main/java/com/esafirm/imagepicker/features/camera/CameraModule.java) -> [CameraModule](https://github.com/nguyenhoanglam/ImagePicker/blob/master/imagepicker/src/main/java/com/nguyenhoanglam/imagepicker/ui/camera/CameraModule.kt)
