### ISSUE TITLE
Why camera permission was removed ?

### ISSUE THREAD

**Issue by DuoBlood** [esafirm/android-image-picker#383]
## Expected Behavior
The lib request camera permission.

## Actual Behavior
The lib does not request camera permission.

## Steps to Reproduce the Problem

  1. Lunch CameraOnlyConfig().

  1. Lunch ImagePickerConfig().
  2. Tap the camera icon.

## Specifications

  - Image Picker Version: 3.0.0-beta4 (742d7b37f99e5682a08883e548eaad9b8352b164)
  - Android OS: 9
  - Phone: Samsung Galaxy S8+

**Comment by cikichen** [comment]
+1
with revoked permission android.permission.CAMERA

**Comment by beom-mingyu** [comment]
me too

**Comment by esafirm** [comment]
Hi @DuoBlood, because we're using camera Intent , I believe we're not needed to request for camera permission.

And it works on my end too. Here's a reference
https://developer.android.com/training/camera/photobasics#TaskManifest

If the issue still happen, can you please attached a video of the issue. Thanks
