### ISSUE TITLE
Option for NO CAMERA PERMISSION?

### ISSUE THREAD

**Issue by pesjak** [esafirm/android-image-picker#79]

**Comment by esafirm** [comment]
@pesjak did you mean no camera permission in the `AndroidManifest`?

**Comment by pesjak** [comment]
Yes because in some cases is not used :).

**Comment by esafirm** [comment]
@pesjak i think the only way to achieve that by separating the `AndroidManifest` with build flavor. And AFAIK in Jitpack there is no way we can release per-flavor. 

So unless you can come up with something else, i guess this is not going to happen.

On the other note, if you using sdk >= 23. You don't have to worry about it, because the permission request is prompted only when the user want to use the camera.

**Comment by esafirm** [comment]
Will closing this for now
